# TCL File Generated by Component Editor 18.1
# Sun May 12 19:58:52 EDT 2019
# DO NOT MODIFY


# 
# sand_top "Sand Toplevel" v1.0
#  2019.05.12.19:58:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sand_top
# 
set_module_property DESCRIPTION ""
set_module_property NAME sand_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Sand Toplevel"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sand_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sand_top.sv SYSTEM_VERILOG PATH modules/sand_top.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group vga
set_module_assignment embeddedsw.dts.name sand_top
set_module_assignment embeddedsw.dts.vendor jjtech


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point kernel
# 
add_interface kernel avalon end
set_interface_property kernel addressUnits WORDS
set_interface_property kernel associatedClock clock
set_interface_property kernel associatedReset reset
set_interface_property kernel bitsPerSymbol 8
set_interface_property kernel burstOnBurstBoundariesOnly false
set_interface_property kernel burstcountUnits WORDS
set_interface_property kernel explicitAddressSpan 0
set_interface_property kernel holdTime 0
set_interface_property kernel linewrapBursts false
set_interface_property kernel maximumPendingReadTransactions 0
set_interface_property kernel maximumPendingWriteTransactions 0
set_interface_property kernel readLatency 0
set_interface_property kernel readWaitTime 1
set_interface_property kernel setupTime 0
set_interface_property kernel timingUnits Cycles
set_interface_property kernel writeWaitTime 0
set_interface_property kernel ENABLED true
set_interface_property kernel EXPORT_OF ""
set_interface_property kernel PORT_NAME_MAP ""
set_interface_property kernel CMSIS_SVD_VARIABLES ""
set_interface_property kernel SVD_ADDRESS_GROUP ""

add_interface_port kernel kernel_chipselect chipselect Input 1
add_interface_port kernel kernel_write write Input 1
add_interface_port kernel kernel_address address Input 3
add_interface_port kernel kernel_writedata writedata Input 8
set_interface_assignment kernel embeddedsw.configuration.isFlash 0
set_interface_assignment kernel embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment kernel embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment kernel embeddedsw.configuration.isPrintableDevice 0

